# Generated by Django 2.2.2 on 2019-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orgprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOrg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
