# Generated by Django 2.2.2 on 2019-07-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volloc',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volloc',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to=settings.AUTH_USER_MODEL),
        ),
    ]
