# Generated by Django 2.2.2 on 2019-07-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volloc_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volloc',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volloc',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
