# Generated by Django 2.2.3 on 2019-07-27 14:30

from django.db import migrations
import location_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190717_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volloc',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='volloc',
            name='long',
        ),
        migrations.AddField(
            model_name='volloc',
            name='location',
            field=location_picker.fields.LocationField(blank=True, max_length=256, null=True),
        ),
    ]
